### ISSUE TITLE
html file is not generated when using different level than desktop.bundles

### ISSUE THREAD

**Issue by kapakos** [bem/project-stub#112]
When I try to use a different level form the one given, i.e. mycustom.bundles, and then run bem make, no html content is generated. I do have created an .bem folder with a level.js file. The content is:
exports.baseLevelPath = require.resolve('../../.bem/levels/bundles.js');

Is there a reason why I cannot use differend *.bundles ?

**Comment by tadatuta** [comment]
@kapakos Hi!
If you use `bem-tools` to build bundles the issue will appear because of build config. It tries to guess which block levels to use depending on bundle name (refer https://github.com/bem/project-stub/blob/bem-core/.bem/make.js#L55).

We have [an issue](https://github.com/bem/project-stub/issues/81) to get rid of such behaviour. But you'd better switch to `ENB` instead of `bem-tools` to build the project (it's also included out of the box).
So you should call `enb make` instead of `bem make` and `enb server` instead of `bem server` (or just `npm start`).

**Comment by kapakos** [comment]
Hi,
thank you very much for the fastest respond ever. Your solution worked like a charm. 
Thank you very much.
